### ISSUE TITLE
Mise à jour vers l'édition Février 2020

### ISSUE THREAD

**Issue by lazouz** [pwbzh/guidesf#1]
Salut, 

Je n'ai pas trop de moyen de te contacter, du coup je le met ici.

Le site https://guidesf.pwbzh.fr/ n'est pas à jour avec la dernière version du guide (février 2020) trouvable à cette adresse https://www.scoutisme-francais.fr/formation
Il serait bien soit de mettre à jour le site, soit de l'éteindre pour ne pas maintenir en ligne une ancienne version du guide :)

On peut t'aider si besoin bien sûr à récupérer le contenu, je ne sais pas trop comment tu avais fait.

Merci à toi ;)

**Comment by pwbzh** [comment]
Hello,

Merci pour ton message :-)
Je n'étais pas au courant de la mise à jour. Je n'ai pas l'impression qu'il y a eu une communication dessus :-(
Je vais mettre à jour et je suis tout à fait ouvert à de l'aide extérieure !

Jusqu'à présent, je relis le guide réglementaire et je mets à jour le code.
J'essaie de voir avec la commission formation SF si on peut se mettre d'accord sur un format d'export.

**Comment by antoinevth** [comment]
Salut !

Je suis également dispo pour aider dans la récupération du contenu, en attendant d'avoir une solution d'export direct !

**Comment by pwbzh** [comment]
J'attends vos pull requests alors ;-)

Je vais ajouter une section contributeurs dans le footer de la page.

**Comment by antoinevth** [comment]
J'ai un peu de temps, je me lance sur la partie **1. Définition des ACM et conditions d'encadrement**.
